# ===============================
# APP
# ===============================
spring.application.name=productapi

# Perfil activo por defecto (para uso local)
spring.profiles.active=dev

# ===============================
# SERVER
# ===============================
server.port=8085

